{% set name = "azure-storage-file-share" %}
{% set version = "12.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 46528bdaadceda06b3c8aee40992e3819649d4aeaf0f41f68e9515f1ea6e8664

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - azure-core >=1.26.0,<2.0.0
    - cryptography >=2.1.4
    - typing_extensions >=4.0.1
    - isodate >=0.6.1
    - msrest >=0.7.1

test:
  imports:
    - azure.storage.fileshare
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-file-share
  summary: Azure Storage File Share client library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - davidbrochart
